name: "deploy-stg"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read
  pull-requests: read

env:
  ENV_NAME: stg
  AWS_ROLE_SESSION_NAME: 0 ## あとで書く
  AWS_ASSUME_ROLE: 0 ## あとで書く
  REGION: ap-northeast-1
  FRONTEND_APP_DIR: app
  VERSION: ${{ github.sha }}

jobs:
  docker-build-and-push:
    name: "docker build and push"
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.short_sha.outputs.sha_short }}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Copy .env file
        run: cp frontend/guide/env/.env.example.${{ env.ENV_NAME }} frontend/guide/.env

      - run: npm
      - name: Install dependencies, and build as standalone app
        run: npm i && npm run build
        working-directory: ./app

      - name: Generate short SHA
        id: short_sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: AWS Assume Role
        uses: aws-actions/configure-aws-credentials@v1
        id: aws_credentials
        with:
          role-to-assume: ${{ env.AWS_ASSUME_ROLE }}
          role-session-name: ${{ env.AWS_ROLE_SESSION_NAME }}
          aws-region: ${{ env.REGION }}

      - name: docker login
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      # - name: docker login
      #   run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - name: sam build
        working-directory: ./app
        run: sam build
      - name: sam deploy
        working-directory: ./app
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-file samconfig.toml --config-env ${{ env.ENV_NAME }}
      # 下記は必要そう
      # - name: Deployment s3
      #   working-directory: ./app
      #   run: aws s3 sync .next/static s3://stg-z-career-frontend-talent/guide/_next/static

      # 下記はいらない？
      # - name: Invalidate CloudFront Cache
      #   run: aws cloudfront create-invalidation --distribution-id E33TE8RXCL6RKE --paths "/guide/*"
